version: '0.2'
language: en

enabled: true
allowCompoundWords: true
useGitignore: true

ignorePaths:
  - build/**
  - node_modules/**
  - .docusaurus/**
  - package-lock.json
  - static/img/**
  - blog/**
  - docs/tutorial-basics/**
  - docs/tutorial-extras/**

files:
  - '**/*.{md,mdx,ts,tsx,js,jsx,json,yaml,yml,css}'

words:
  - Corekraft
  - ATDD
  - Avenir
  - BDD
  - Docusaurus
  - DX
  - GitHub
  - mdx
  - orgs
  - Salesforce
  - sfdx
  - trunkbaseddevelopment # trunkbaseddevelopment.com
  - minimumcd # minimumcd.org
  - autorabit # tool for orchestration and deploying in salesforce
  - flexipage # metadata for lightning record pages
  - flexipages
  - gitflow

ignoreWords: []

dictionaries:
  - softwareTerms
  - companies
